# 开发环境
server:
  port: 8080
#关闭thymeleaf缓存      数据库配置
spring:
  thymeleaf:
    cache: false
#    mode: HTML5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.166.78:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: ZEye20010725#
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
  redis:
    host: 39.108.166.78
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
        max-wait: -1



mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: info
    com.zeye.blog : debug
  file:
    name: log/blog.log
